/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Greeter, GreeterInterface } from "../Greeter";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "h",
        type: "string",
      },
    ],
    name: "sayHello",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b506102948061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063c3a9b1c51461002d575b5f5ffd5b61004061003b366004610160565b610056565b60405161004d9190610213565b60405180910390f35b6040517f68656c6c6f20466f7264656669210000000000000000000000000000000000006020820152606090602e0160405160208183030381529060405280519060200120826040516020016100ac9190610248565b60405160208183030381529060405280519060200120146101135760405162461bcd60e51b815260206004820152601760248201527f6d757374207361792068656c6c6f20466f726465666921000000000000000000604482015260640160405180910390fd5b505060408051808201909152600681527f68656c6c6f210000000000000000000000000000000000000000000000000000602082015290565b634e487b7160e01b5f52604160045260245ffd5b5f60208284031215610170575f5ffd5b813567ffffffffffffffff811115610186575f5ffd5b8201601f81018413610196575f5ffd5b803567ffffffffffffffff8111156101b0576101b061014c565b604051601f8201601f19908116603f0116810167ffffffffffffffff811182821017156101df576101df61014c565b6040528181528282016020018610156101f6575f5ffd5b816020840160208301375f91810160200191909152949350505050565b602081525f82518060208401528060208501604085015e5f604082850101526040601f19601f83011684010191505092915050565b5f82518060208501845e5f92019182525091905056fea264697066735822122095ba859c2c650b77bf863e094416436cbc4885a43ee2f39df5813af91b14afaf64736f6c634300081e0033";

type GreeterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GreeterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Greeter__factory extends ContractFactory {
  constructor(...args: GreeterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Greeter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Greeter__factory {
    return super.connect(runner) as Greeter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GreeterInterface {
    return new Interface(_abi) as GreeterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Greeter {
    return new Contract(address, _abi, runner) as unknown as Greeter;
  }
}
