[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
batcher_program = "BTCH6Wx6XdS8epLM4qZtuLeUebvBCzVPS4WAcQgPQw6t"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/cli/cli-key.json"

[scripts]
test = "cargo test"

[hooks]
