/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { isProgramError, type Address, type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM, type SolanaError } from '@solana/kit';
import { BATCHER_PROGRAM_PROGRAM_ADDRESS } from '../programs';

/** EmptyTransferList: Transfer list is empty */
export const BATCHER_PROGRAM_ERROR__EMPTY_TRANSFER_LIST = 0x1770; // 6000
/** AccountCountMismatch: Number of remaining accounts does not match the number of transfers */
export const BATCHER_PROGRAM_ERROR__ACCOUNT_COUNT_MISMATCH = 0x1771; // 6001
/** InvalidTokenAccount: A provided account is not a valid SPL token account */
export const BATCHER_PROGRAM_ERROR__INVALID_TOKEN_ACCOUNT = 0x1772; // 6002
/** MintMismatch: Destination token account mint does not match source mint */
export const BATCHER_PROGRAM_ERROR__MINT_MISMATCH = 0x1773; // 6003
/** ArithmeticOverflow: Total transfer amount overflows u64 */
export const BATCHER_PROGRAM_ERROR__ARITHMETIC_OVERFLOW = 0x1774; // 6004
/** MaxTransfersExceeded: Exceeds maximum number of transfers per batch */
export const BATCHER_PROGRAM_ERROR__MAX_TRANSFERS_EXCEEDED = 0x1775; // 6005
/** InvalidTokenProgram: Invalid token program: must be Token or Token-2022 */
export const BATCHER_PROGRAM_ERROR__INVALID_TOKEN_PROGRAM = 0x1776; // 6006

export type BatcherProgramError = typeof BATCHER_PROGRAM_ERROR__ACCOUNT_COUNT_MISMATCH | typeof BATCHER_PROGRAM_ERROR__ARITHMETIC_OVERFLOW | typeof BATCHER_PROGRAM_ERROR__EMPTY_TRANSFER_LIST | typeof BATCHER_PROGRAM_ERROR__INVALID_TOKEN_ACCOUNT | typeof BATCHER_PROGRAM_ERROR__INVALID_TOKEN_PROGRAM | typeof BATCHER_PROGRAM_ERROR__MAX_TRANSFERS_EXCEEDED | typeof BATCHER_PROGRAM_ERROR__MINT_MISMATCH;

let batcherProgramErrorMessages: Record<BatcherProgramError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  batcherProgramErrorMessages = { [BATCHER_PROGRAM_ERROR__ACCOUNT_COUNT_MISMATCH]: `Number of remaining accounts does not match the number of transfers`, [BATCHER_PROGRAM_ERROR__ARITHMETIC_OVERFLOW]: `Total transfer amount overflows u64`, [BATCHER_PROGRAM_ERROR__EMPTY_TRANSFER_LIST]: `Transfer list is empty`, [BATCHER_PROGRAM_ERROR__INVALID_TOKEN_ACCOUNT]: `A provided account is not a valid SPL token account`, [BATCHER_PROGRAM_ERROR__INVALID_TOKEN_PROGRAM]: `Invalid token program: must be Token or Token-2022`, [BATCHER_PROGRAM_ERROR__MAX_TRANSFERS_EXCEEDED]: `Exceeds maximum number of transfers per batch`, [BATCHER_PROGRAM_ERROR__MINT_MISMATCH]: `Destination token account mint does not match source mint` };
}

export function getBatcherProgramErrorMessage(code: BatcherProgramError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (batcherProgramErrorMessages as Record<BatcherProgramError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isBatcherProgramError<TProgramErrorCode extends BatcherProgramError>(
    error: unknown,
    transactionMessage: { instructions: Record<number, { programAddress: Address }> },
    code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> & Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(error, transactionMessage, BATCHER_PROGRAM_PROGRAM_ADDRESS, code);
}