/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getArrayDecoder, getArrayEncoder, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type Codec, type Decoder, type Encoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyAccount, type ReadonlyUint8Array, type TransactionSigner, type WritableAccount, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, type ResolvedInstructionAccount } from '@solana/program-client-core';
import { BATCHER_PROGRAM_PROGRAM_ADDRESS } from '../programs';

export const BATCH_TRANSFER_SAME_TOKEN_DISCRIMINATOR = new Uint8Array([36, 84, 135, 229, 237, 109, 201, 122]);

export function getBatchTransferSameTokenDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(BATCH_TRANSFER_SAME_TOKEN_DISCRIMINATOR); }

export type BatchTransferSameTokenInstruction<TProgram extends string = typeof BATCHER_PROGRAM_PROGRAM_ADDRESS, TAccountSender extends string | AccountMeta<string> = string, TAccountSenderTokenAccount extends string | AccountMeta<string> = string, TAccountTokenProgram extends string | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSender extends string ? WritableSignerAccount<TAccountSender> & AccountSignerMeta<TAccountSender> : TAccountSender, TAccountSenderTokenAccount extends string ? WritableAccount<TAccountSenderTokenAccount> : TAccountSenderTokenAccount, TAccountTokenProgram extends string ? ReadonlyAccount<TAccountTokenProgram> : TAccountTokenProgram, ...TRemainingAccounts]>;

export type BatchTransferSameTokenInstructionData = { discriminator: ReadonlyUint8Array; amounts: Array<bigint>;  };

export type BatchTransferSameTokenInstructionDataArgs = { amounts: Array<number | bigint>;  };

export function getBatchTransferSameTokenInstructionDataEncoder(): Encoder<BatchTransferSameTokenInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['amounts', getArrayEncoder(getU64Encoder())]]), (value) => ({ ...value, discriminator: BATCH_TRANSFER_SAME_TOKEN_DISCRIMINATOR }));
}

export function getBatchTransferSameTokenInstructionDataDecoder(): Decoder<BatchTransferSameTokenInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['amounts', getArrayDecoder(getU64Decoder())]]);
}

export function getBatchTransferSameTokenInstructionDataCodec(): Codec<BatchTransferSameTokenInstructionDataArgs, BatchTransferSameTokenInstructionData> {
    return combineCodec(getBatchTransferSameTokenInstructionDataEncoder(), getBatchTransferSameTokenInstructionDataDecoder());
}

export type BatchTransferSameTokenInput<TAccountSender extends string = string, TAccountSenderTokenAccount extends string = string, TAccountTokenProgram extends string = string> =  {
  sender: TransactionSigner<TAccountSender>;
senderTokenAccount: Address<TAccountSenderTokenAccount>;
tokenProgram?: Address<TAccountTokenProgram>;
amounts: BatchTransferSameTokenInstructionDataArgs["amounts"];
}

export function getBatchTransferSameTokenInstruction<TAccountSender extends string, TAccountSenderTokenAccount extends string, TAccountTokenProgram extends string, TProgramAddress extends Address = typeof BATCHER_PROGRAM_PROGRAM_ADDRESS>(input: BatchTransferSameTokenInput<TAccountSender, TAccountSenderTokenAccount, TAccountTokenProgram>, config?: { programAddress?: TProgramAddress } ): BatchTransferSameTokenInstruction<TProgramAddress, TAccountSender, TAccountSenderTokenAccount, TAccountTokenProgram> {
  // Program address.
const programAddress = config?.programAddress ?? BATCHER_PROGRAM_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { sender: { value: input.sender ?? null, isWritable: true }, senderTokenAccount: { value: input.senderTokenAccount ?? null, isWritable: true }, tokenProgram: { value: input.tokenProgram ?? null, isWritable: false } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };


// Resolve default values.
if (!accounts.tokenProgram.value) {
accounts.tokenProgram.value = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
}

const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta("sender", accounts.sender), getAccountMeta("senderTokenAccount", accounts.senderTokenAccount), getAccountMeta("tokenProgram", accounts.tokenProgram)], data: getBatchTransferSameTokenInstructionDataEncoder().encode(args as BatchTransferSameTokenInstructionDataArgs), programAddress } as BatchTransferSameTokenInstruction<TProgramAddress, TAccountSender, TAccountSenderTokenAccount, TAccountTokenProgram>);
}

export type ParsedBatchTransferSameTokenInstruction<TProgram extends string = typeof BATCHER_PROGRAM_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
sender: TAccountMetas[0];
senderTokenAccount: TAccountMetas[1];
tokenProgram: TAccountMetas[2];
};
data: BatchTransferSameTokenInstructionData; };

export function parseBatchTransferSameTokenInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedBatchTransferSameTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 3 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { sender: getNextAccount(), senderTokenAccount: getNextAccount(), tokenProgram: getNextAccount() }, data: getBatchTransferSameTokenInstructionDataDecoder().decode(instruction.data) };
}