/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { combineCodec, fixDecoderSize, fixEncoderSize, getArrayDecoder, getArrayEncoder, getBytesDecoder, getBytesEncoder, getStructDecoder, getStructEncoder, getU64Decoder, getU64Encoder, SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, SolanaError, transformEncoder, type AccountMeta, type AccountSignerMeta, type Address, type Codec, type Decoder, type Encoder, type Instruction, type InstructionWithAccounts, type InstructionWithData, type ReadonlyUint8Array, type TransactionSigner, type WritableSignerAccount } from '@solana/kit';
import { getAccountMetaFactory, type ResolvedInstructionAccount } from '@solana/program-client-core';
import { BATCHER_PROGRAM_PROGRAM_ADDRESS } from '../programs';

export const BATCH_TRANSFER_MULTI_TOKEN_DISCRIMINATOR = new Uint8Array([46, 222, 3, 26, 60, 64, 247, 209]);

export function getBatchTransferMultiTokenDiscriminatorBytes() { return fixEncoderSize(getBytesEncoder(), 8).encode(BATCH_TRANSFER_MULTI_TOKEN_DISCRIMINATOR); }

export type BatchTransferMultiTokenInstruction<TProgram extends string = typeof BATCHER_PROGRAM_PROGRAM_ADDRESS, TAccountSender extends string | AccountMeta<string> = string, TRemainingAccounts extends readonly AccountMeta<string>[] = []> =
Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array> & InstructionWithAccounts<[TAccountSender extends string ? WritableSignerAccount<TAccountSender> & AccountSignerMeta<TAccountSender> : TAccountSender, ...TRemainingAccounts]>;

export type BatchTransferMultiTokenInstructionData = { discriminator: ReadonlyUint8Array; amounts: Array<bigint>;  };

export type BatchTransferMultiTokenInstructionDataArgs = { amounts: Array<number | bigint>;  };

export function getBatchTransferMultiTokenInstructionDataEncoder(): Encoder<BatchTransferMultiTokenInstructionDataArgs> {
    return transformEncoder(getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)], ['amounts', getArrayEncoder(getU64Encoder())]]), (value) => ({ ...value, discriminator: BATCH_TRANSFER_MULTI_TOKEN_DISCRIMINATOR }));
}

export function getBatchTransferMultiTokenInstructionDataDecoder(): Decoder<BatchTransferMultiTokenInstructionData> {
    return getStructDecoder([['discriminator', fixDecoderSize(getBytesDecoder(), 8)], ['amounts', getArrayDecoder(getU64Decoder())]]);
}

export function getBatchTransferMultiTokenInstructionDataCodec(): Codec<BatchTransferMultiTokenInstructionDataArgs, BatchTransferMultiTokenInstructionData> {
    return combineCodec(getBatchTransferMultiTokenInstructionDataEncoder(), getBatchTransferMultiTokenInstructionDataDecoder());
}

export type BatchTransferMultiTokenInput<TAccountSender extends string = string> =  {
  sender: TransactionSigner<TAccountSender>;
amounts: BatchTransferMultiTokenInstructionDataArgs["amounts"];
}

export function getBatchTransferMultiTokenInstruction<TAccountSender extends string, TProgramAddress extends Address = typeof BATCHER_PROGRAM_PROGRAM_ADDRESS>(input: BatchTransferMultiTokenInput<TAccountSender>, config?: { programAddress?: TProgramAddress } ): BatchTransferMultiTokenInstruction<TProgramAddress, TAccountSender> {
  // Program address.
const programAddress = config?.programAddress ?? BATCHER_PROGRAM_PROGRAM_ADDRESS;

 // Original accounts.
const originalAccounts = { sender: { value: input.sender ?? null, isWritable: true } }
const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedInstructionAccount>;


// Original args.
const args = { ...input,  };




const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
return Object.freeze({ accounts: [getAccountMeta("sender", accounts.sender)], data: getBatchTransferMultiTokenInstructionDataEncoder().encode(args as BatchTransferMultiTokenInstructionDataArgs), programAddress } as BatchTransferMultiTokenInstruction<TProgramAddress, TAccountSender>);
}

export type ParsedBatchTransferMultiTokenInstruction<TProgram extends string = typeof BATCHER_PROGRAM_PROGRAM_ADDRESS, TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]> = { programAddress: Address<TProgram>;
accounts: {
sender: TAccountMetas[0];
};
data: BatchTransferMultiTokenInstructionData; };

export function parseBatchTransferMultiTokenInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>): ParsedBatchTransferMultiTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
  throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS, { actualAccountMetas: instruction.accounts.length, expectedAccountMetas: 1 });
}
let accountIndex = 0;
const getNextAccount = () => {
  const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
  accountIndex += 1;
  return accountMeta;
}
  return { programAddress: instruction.programAddress, accounts: { sender: getNextAccount() }, data: getBatchTransferMultiTokenInstructionDataDecoder().decode(instruction.data) };
}