/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import { assertIsInstructionWithAccounts, containsBytes, fixEncoderSize, getBytesEncoder, SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION, SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE, SolanaError, type Address, type ClientWithTransactionPlanning, type ClientWithTransactionSending, type Instruction, type InstructionWithData, type ReadonlyUint8Array } from '@solana/kit';
import { addSelfPlanAndSendFunctions, type SelfPlanAndSendFunctions } from '@solana/program-client-core';
import { getBatchTransferMultiTokenInstruction, getBatchTransferSameTokenInstruction, parseBatchTransferMultiTokenInstruction, parseBatchTransferSameTokenInstruction, type BatchTransferMultiTokenInput, type BatchTransferSameTokenInput, type ParsedBatchTransferMultiTokenInstruction, type ParsedBatchTransferSameTokenInstruction } from '../instructions';

export const BATCHER_PROGRAM_PROGRAM_ADDRESS = 'BTCH6Wx6XdS8epLM4qZtuLeUebvBCzVPS4WAcQgPQw6t' as Address<'BTCH6Wx6XdS8epLM4qZtuLeUebvBCzVPS4WAcQgPQw6t'>;

export enum BatcherProgramInstruction { BatchTransferMultiToken, BatchTransferSameToken }

export function identifyBatcherProgramInstruction(instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array): BatcherProgramInstruction {
    const data = 'data' in instruction ? instruction.data : instruction;
    if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([46, 222, 3, 26, 60, 64, 247, 209])), 0)) { return BatcherProgramInstruction.BatchTransferMultiToken; }
if (containsBytes(data, fixEncoderSize(getBytesEncoder(), 8).encode(new Uint8Array([36, 84, 135, 229, 237, 109, 201, 122])), 0)) { return BatcherProgramInstruction.BatchTransferSameToken; }
    throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION, { instructionData: data, programName: "batcherProgram" });
}

export type ParsedBatcherProgramInstruction<TProgram extends string = 'BTCH6Wx6XdS8epLM4qZtuLeUebvBCzVPS4WAcQgPQw6t'> =
| { instructionType: BatcherProgramInstruction.BatchTransferMultiToken } & ParsedBatchTransferMultiTokenInstruction<TProgram>
| { instructionType: BatcherProgramInstruction.BatchTransferSameToken } & ParsedBatchTransferSameTokenInstruction<TProgram>


        export function parseBatcherProgramInstruction<TProgram extends string>(
            instruction: Instruction<TProgram> 
                & InstructionWithData<ReadonlyUint8Array>
        ): ParsedBatcherProgramInstruction<TProgram> {
            const instructionType = identifyBatcherProgramInstruction(instruction);
            switch (instructionType) {
                case BatcherProgramInstruction.BatchTransferMultiToken: { assertIsInstructionWithAccounts(instruction);
return { instructionType: BatcherProgramInstruction.BatchTransferMultiToken, ...parseBatchTransferMultiTokenInstruction(instruction) }; }
case BatcherProgramInstruction.BatchTransferSameToken: { assertIsInstructionWithAccounts(instruction);
return { instructionType: BatcherProgramInstruction.BatchTransferSameToken, ...parseBatchTransferSameTokenInstruction(instruction) }; }
                default: throw new SolanaError(SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE, { instructionType: instructionType as string, programName: "batcherProgram" });
            }
        }

export type BatcherProgramPlugin = { instructions: BatcherProgramPluginInstructions; }

export type BatcherProgramPluginInstructions = { batchTransferMultiToken: (input: BatchTransferMultiTokenInput) => ReturnType<typeof getBatchTransferMultiTokenInstruction> & SelfPlanAndSendFunctions; batchTransferSameToken: (input: BatchTransferSameTokenInput) => ReturnType<typeof getBatchTransferSameTokenInstruction> & SelfPlanAndSendFunctions; }

export type BatcherProgramPluginRequirements = ClientWithTransactionPlanning & ClientWithTransactionSending

export function batcherProgramProgram() {
    return <T extends BatcherProgramPluginRequirements>(client: T) => {
        return { ...client, batcherProgram: <BatcherProgramPlugin>{ instructions: { batchTransferMultiToken: input => addSelfPlanAndSendFunctions(client, getBatchTransferMultiTokenInstruction(input)), batchTransferSameToken: input => addSelfPlanAndSendFunctions(client, getBatchTransferSameTokenInstruction(input)) } } };
    };
}